# Generated by Django 2.2.17 on 2020-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioContent',
            new_name='ContentAudio',
        ),
        migrations.RenameModel(
            old_name='TextContent',
            new_name='ContentText',
        ),
        migrations.RenameModel(
            old_name='VideoContent',
            new_name='ContentVideo',
        ),
    ]
